"""initial schema

Revision ID: be8b8a58d6f1
Revises: 
Create Date: 2026-07-30 19:04:53.560717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be8b8a58d6f1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_id', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('avatar_hash', sa.String(length=255), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_discord_id'), 'users', ['discord_id'], unique=True)
    op.create_table('guilds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('discord_guild_id', sa.String(length=32), nullable=False),
    sa.Column('wcl_guild_name', sa.String(length=255), nullable=True),
    sa.Column('server_slug', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=8), nullable=False),
    sa.Column('raid_helper_api_key', sa.String(length=255), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guilds_discord_guild_id'), 'guilds', ['discord_guild_id'], unique=True)
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('class_name', sa.String(length=32), nullable=False),
    sa.Column('spec', sa.String(length=64), nullable=True),
    sa.Column('role', sa.Enum('tank', 'healer', 'dps', name='characterrole'), nullable=True),
    sa.Column('discord_user_id', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characters_discord_user_id'), 'characters', ['discord_user_id'], unique=False)
    op.create_table('guild_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'officer', name='membershiprole'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'user_id', name='uq_membership_guild_user')
    )
    op.create_table('raid_tiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('zone', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('encounters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raid_tier_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['raid_tier_id'], ['raid_tiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gear_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('wcl_report', 'manual', name='gearsource'), nullable=False),
    sa.Column('source_report_code', sa.String(length=32), nullable=True),
    sa.Column('avg_ilvl', sa.Float(), nullable=False),
    sa.Column('gear_json', sa.JSON(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gear_snapshots_character_id'), 'gear_snapshots', ['character_id'], unique=False)
    op.create_table('raid_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raid_tier_id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raid_helper_event_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('planned', 'completed', 'cancelled', name='raideventstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.ForeignKeyConstraint(['raid_tier_id'], ['raid_tiers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raid_helper_event_id')
    )
    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raid_event_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('group_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['raid_event_id'], ['raid_events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raid_event_id', 'character_id', name='uq_assignment_event_char')
    )
    op.create_table('encounter_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raid_event_id', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.ForeignKeyConstraint(['raid_event_id'], ['raid_events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raid_event_id', 'encounter_id', name='uq_note_event_encounter')
    )
    op.create_table('raid_helper_signups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raid_event_id', sa.Integer(), nullable=False),
    sa.Column('raid_helper_signup_id', sa.String(length=64), nullable=False),
    sa.Column('discord_user_id', sa.String(length=32), nullable=False),
    sa.Column('discord_username', sa.String(length=255), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('class_spec', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('raw_json', sa.JSON(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['raid_event_id'], ['raid_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raid_helper_signups_discord_user_id'), 'raid_helper_signups', ['discord_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raid_helper_signups_discord_user_id'), table_name='raid_helper_signups')
    op.drop_table('raid_helper_signups')
    op.drop_table('encounter_notes')
    op.drop_table('assignments')
    op.drop_table('raid_events')
    op.drop_index(op.f('ix_gear_snapshots_character_id'), table_name='gear_snapshots')
    op.drop_table('gear_snapshots')
    op.drop_table('encounters')
    op.drop_table('raid_tiers')
    op.drop_table('guild_memberships')
    op.drop_index(op.f('ix_characters_discord_user_id'), table_name='characters')
    op.drop_table('characters')
    op.drop_index(op.f('ix_guilds_discord_guild_id'), table_name='guilds')
    op.drop_table('guilds')
    op.drop_index(op.f('ix_users_discord_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
